/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as QuestionsRouteImport } from './routes/questions'
import { Route as MemberRouteImport } from './routes/member'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemberIndexRouteImport } from './routes/member.index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as MemberPlanRouteImport } from './routes/member.plan'
import { Route as MemberLearnRouteImport } from './routes/member.learn'
import { Route as MemberFindAttorneyRouteImport } from './routes/member.find-attorney'
import { Route as MemberDocumentsRouteImport } from './routes/member.documents'
import { Route as MemberAssistantRouteImport } from './routes/member.assistant'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsRoute = QuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRoute = MemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberIndexRoute = MemberIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemberRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberPlanRoute = MemberPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => MemberRoute,
} as any)
const MemberLearnRoute = MemberLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => MemberRoute,
} as any)
const MemberFindAttorneyRoute = MemberFindAttorneyRouteImport.update({
  id: '/find-attorney',
  path: '/find-attorney',
  getParentRoute: () => MemberRoute,
} as any)
const MemberDocumentsRoute = MemberDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => MemberRoute,
} as any)
const MemberAssistantRoute = MemberAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => MemberRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/member': typeof MemberRouteWithChildren
  '/questions': typeof QuestionsRoute
  '/rules': typeof RulesRoute
  '/templates': typeof TemplatesRoute
  '/api/chat': typeof ApiChatRoute
  '/member/assistant': typeof MemberAssistantRoute
  '/member/documents': typeof MemberDocumentsRoute
  '/member/find-attorney': typeof MemberFindAttorneyRoute
  '/member/learn': typeof MemberLearnRoute
  '/member/plan': typeof MemberPlanRoute
  '/share/$token': typeof ShareTokenRoute
  '/member/': typeof MemberIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/questions': typeof QuestionsRoute
  '/rules': typeof RulesRoute
  '/templates': typeof TemplatesRoute
  '/api/chat': typeof ApiChatRoute
  '/member/assistant': typeof MemberAssistantRoute
  '/member/documents': typeof MemberDocumentsRoute
  '/member/find-attorney': typeof MemberFindAttorneyRoute
  '/member/learn': typeof MemberLearnRoute
  '/member/plan': typeof MemberPlanRoute
  '/share/$token': typeof ShareTokenRoute
  '/member': typeof MemberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/member': typeof MemberRouteWithChildren
  '/questions': typeof QuestionsRoute
  '/rules': typeof RulesRoute
  '/templates': typeof TemplatesRoute
  '/api/chat': typeof ApiChatRoute
  '/member/assistant': typeof MemberAssistantRoute
  '/member/documents': typeof MemberDocumentsRoute
  '/member/find-attorney': typeof MemberFindAttorneyRoute
  '/member/learn': typeof MemberLearnRoute
  '/member/plan': typeof MemberPlanRoute
  '/share/$token': typeof ShareTokenRoute
  '/member/': typeof MemberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/faq'
    | '/member'
    | '/questions'
    | '/rules'
    | '/templates'
    | '/api/chat'
    | '/member/assistant'
    | '/member/documents'
    | '/member/find-attorney'
    | '/member/learn'
    | '/member/plan'
    | '/share/$token'
    | '/member/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/questions'
    | '/rules'
    | '/templates'
    | '/api/chat'
    | '/member/assistant'
    | '/member/documents'
    | '/member/find-attorney'
    | '/member/learn'
    | '/member/plan'
    | '/share/$token'
    | '/member'
  id:
    | '__root__'
    | '/'
    | '/faq'
    | '/member'
    | '/questions'
    | '/rules'
    | '/templates'
    | '/api/chat'
    | '/member/assistant'
    | '/member/documents'
    | '/member/find-attorney'
    | '/member/learn'
    | '/member/plan'
    | '/share/$token'
    | '/member/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  MemberRoute: typeof MemberRouteWithChildren
  QuestionsRoute: typeof QuestionsRoute
  RulesRoute: typeof RulesRoute
  TemplatesRoute: typeof TemplatesRoute
  ApiChatRoute: typeof ApiChatRoute
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions': {
      id: '/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof QuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/': {
      id: '/member/'
      path: '/'
      fullPath: '/member/'
      preLoaderRoute: typeof MemberIndexRouteImport
      parentRoute: typeof MemberRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/plan': {
      id: '/member/plan'
      path: '/plan'
      fullPath: '/member/plan'
      preLoaderRoute: typeof MemberPlanRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/learn': {
      id: '/member/learn'
      path: '/learn'
      fullPath: '/member/learn'
      preLoaderRoute: typeof MemberLearnRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/find-attorney': {
      id: '/member/find-attorney'
      path: '/find-attorney'
      fullPath: '/member/find-attorney'
      preLoaderRoute: typeof MemberFindAttorneyRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/documents': {
      id: '/member/documents'
      path: '/documents'
      fullPath: '/member/documents'
      preLoaderRoute: typeof MemberDocumentsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/assistant': {
      id: '/member/assistant'
      path: '/assistant'
      fullPath: '/member/assistant'
      preLoaderRoute: typeof MemberAssistantRouteImport
      parentRoute: typeof MemberRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MemberRouteChildren {
  MemberAssistantRoute: typeof MemberAssistantRoute
  MemberDocumentsRoute: typeof MemberDocumentsRoute
  MemberFindAttorneyRoute: typeof MemberFindAttorneyRoute
  MemberLearnRoute: typeof MemberLearnRoute
  MemberPlanRoute: typeof MemberPlanRoute
  MemberIndexRoute: typeof MemberIndexRoute
}

const MemberRouteChildren: MemberRouteChildren = {
  MemberAssistantRoute: MemberAssistantRoute,
  MemberDocumentsRoute: MemberDocumentsRoute,
  MemberFindAttorneyRoute: MemberFindAttorneyRoute,
  MemberLearnRoute: MemberLearnRoute,
  MemberPlanRoute: MemberPlanRoute,
  MemberIndexRoute: MemberIndexRoute,
}

const MemberRouteWithChildren =
  MemberRoute._addFileChildren(MemberRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  MemberRoute: MemberRouteWithChildren,
  QuestionsRoute: QuestionsRoute,
  RulesRoute: RulesRoute,
  TemplatesRoute: TemplatesRoute,
  ApiChatRoute: ApiChatRoute,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
